<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\JulOS.Application\JulOS.Application.csproj" />
    <ProjectReference Include="..\JulOS.Domain\JulOS.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="JulOS.Infrastructure.Tests" />
    <InternalsVisibleTo Include="JulOS.Integration.Tests" />
  </ItemGroup>

</Project>
