// <auto-generated />
using System;
using JulOS.Infrastructure.Persistence.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JulOS.Infrastructure.Persistence.Core.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20260802081946_InitialCorePersistence")]
    partial class InitialCorePersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JulOS.Infrastructure.Persistence.Core.AgentCapabilityRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<string>("CapabilityName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("capability_name");

                    b.Property<int>("CapabilityVersion")
                        .HasColumnType("integer")
                        .HasColumnName("capability_version");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)")
                        .HasColumnName("metadata");

                    b.Property<int>("MetadataVersion")
                        .HasColumnType("integer")
                        .HasColumnName("metadata_version");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at_utc");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.HasKey("Id")
                        .HasName("pk_agent_capabilities");

                    b.HasIndex("AgentId", "CapabilityName")
                        .IsUnique()
                        .HasDatabaseName("ux_agent_capabilities_agent_name");

                    b.ToTable("agent_capabilities", "core", t =>
                        {
                            t.HasCheckConstraint("ck_agent_capabilities_metadata_length", "char_length(metadata) <= 8192");

                            t.HasCheckConstraint("ck_agent_capabilities_revision", "revision >= 1");

                            t.HasCheckConstraint("ck_agent_capabilities_version", "capability_version >= 1 AND metadata_version >= 1");
                        });
                });

            modelBuilder.Entity("JulOS.Infrastructure.Persistence.Core.AgentRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("architecture");

                    b.Property<DateTimeOffset>("EnrolledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at_utc");

                    b.Property<DateTimeOffset?>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("MachineIdentity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("machine_identity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("operating_system");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("state");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_agents");

                    b.HasIndex("MachineIdentity")
                        .HasDatabaseName("ix_agents_machine_identity");

                    b.ToTable("agents", "core", t =>
                        {
                            t.HasCheckConstraint("ck_agents_revision", "revision >= 1");

                            t.HasCheckConstraint("ck_agents_revoked_at", "(state = 'Revoked' AND revoked_at_utc IS NOT NULL) OR (state <> 'Revoked' AND revoked_at_utc IS NULL)");
                        });
                });

            modelBuilder.Entity("JulOS.Infrastructure.Persistence.Core.ApplicationDefinitionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DefaultHeight")
                        .HasColumnType("integer")
                        .HasColumnName("default_height");

                    b.Property<int>("DefaultWidth")
                        .HasColumnType("integer")
                        .HasColumnName("default_width");

                    b.Property<string>("DisplayNameKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name_key");

                    b.Property<string>("InstancePolicy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("instance_policy");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<int>("MinimumHeight")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_height");

                    b.Property<int>("MinimumWidth")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_width");

                    b.Property<string>("OwningPackageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("owning_package_id");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("StableKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stable_key");

                    b.HasKey("Id")
                        .HasName("pk_application_definitions");

                    b.HasIndex("OwningPackageId", "StableKey")
                        .IsUnique()
                        .HasDatabaseName("ux_application_definitions_package_stable_key");

                    b.ToTable("application_definitions", "core", t =>
                        {
                            t.HasCheckConstraint("ck_application_definitions_revision", "revision >= 1");

                            t.HasCheckConstraint("ck_application_definitions_window_size", "minimum_width BETWEEN 120 AND 16384 AND minimum_height BETWEEN 120 AND 16384 AND default_width BETWEEN minimum_width AND 16384 AND default_height BETWEEN minimum_height AND 16384");
                        });
                });

            modelBuilder.Entity("JulOS.Infrastructure.Persistence.Core.ApplicationViewportRow", b =>
                {
                    b.Property<Guid>("ApplicationDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_definition_id");

                    b.Property<string>("ViewportClass")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("viewport_class");

                    b.HasKey("ApplicationDefinitionId", "ViewportClass")
                        .HasName("pk_application_viewports");

                    b.ToTable("application_viewports", "core");
                });

            modelBuilder.Entity("JulOS.Infrastructure.Persistence.Core.AuditEventRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("action");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("outcome");

                    b.Property<string>("RemoteAddress")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("remote_address");

                    b.Property<string>("SafeDetails")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)")
                        .HasColumnName("safe_details");

                    b.Property<string>("SourcePackageId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_package_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("summary");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target_type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_audit_events_occurred_at_utc");

                    b.ToTable("audit_events", "core");
                });

            modelBuilder.Entity("JulOS.Infrastructure.Persistence.Core.DesktopLayoutRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("ViewportClass")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("viewport_class");

                    b.HasKey("Id")
                        .HasName("pk_desktop_layouts");

                    b.HasIndex("UserId", "ViewportClass")
                        .IsUnique()
                        .HasDatabaseName("ux_desktop_layouts_default_per_viewport")
                        .HasFilter("is_default");

                    b.HasIndex("UserId", "ViewportClass", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_desktop_layouts_user_viewport_name");

                    b.ToTable("desktop_layouts", "core", t =>
                        {
                            t.HasCheckConstraint("ck_desktop_layouts_revision", "revision >= 1");
                        });
                });

            modelBuilder.Entity("JulOS.Infrastructure.Persistence.Core.DesktopWindowRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_definition_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DesktopLayoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("desktop_layout_id");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<Guid?>("LaunchTargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("launch_target_id");

                    b.Property<int>("RestoreHeight")
                        .HasColumnType("integer")
                        .HasColumnName("restore_height");

                    b.Property<int>("RestoreWidth")
                        .HasColumnType("integer")
                        .HasColumnName("restore_width");

                    b.Property<int>("RestoreX")
                        .HasColumnType("integer")
                        .HasColumnName("restore_x");

                    b.Property<int>("RestoreY")
                        .HasColumnType("integer")
                        .HasColumnName("restore_y");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<Guid?>("SessionReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_reference_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.Property<int>("X")
                        .HasColumnType("integer")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("integer")
                        .HasColumnName("y");

                    b.Property<int>("ZIndex")
                        .HasColumnType("integer")
                        .HasColumnName("z_index");

                    b.HasKey("Id")
                        .HasName("pk_desktop_windows");

                    b.HasIndex("ApplicationDefinitionId");

                    b.HasIndex("LaunchTargetId");

                    b.HasIndex("SessionReferenceId");

                    b.HasIndex("DesktopLayoutId", "ZIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_desktop_windows_layout_z_index");

                    b.ToTable("desktop_windows", "core", t =>
                        {
                            t.HasCheckConstraint("ck_desktop_windows_bounds", "width BETWEEN 1 AND 16384 AND height BETWEEN 1 AND 16384 AND restore_width BETWEEN 1 AND 16384 AND restore_height BETWEEN 1 AND 16384 AND abs(x) <= 65536 AND abs(y) <= 65536 AND abs(restore_x) <= 65536 AND abs(restore_y) <= 65536");

                            t.HasCheckConstraint("ck_desktop_windows_revision", "revision >= 1");

                            t.HasCheckConstraint("ck_desktop_windows_z_index", "z_index >= 0");
                        });
                });

            modelBuilder.Entity("JulOS.Infrastructure.Persistence.Core.LaunchTargetRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_definition_id");

                    b.Property<string>("ApprovalState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("approval_state");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at_utc");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("ExternalIdentity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_identity");

                    b.Property<DateTimeOffset>("FirstObservedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_observed_at_utc");

                    b.Property<DateTimeOffset>("LastObservedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_observed_at_utc");

                    b.Property<string>("OwningPackageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("owning_package_id");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.HasKey("Id")
                        .HasName("pk_launch_targets");

                    b.HasIndex("ApplicationDefinitionId");

                    b.HasIndex("OwningPackageId", "ExternalIdentity")
                        .IsUnique()
                        .HasDatabaseName("ux_launch_targets_package_external_identity");

                    b.ToTable("launch_targets", "core", t =>
                        {
                            t.HasCheckConstraint("ck_launch_targets_approval", "(approval_state = 'Approved' AND approved_at_utc IS NOT NULL AND approved_by_user_id IS NOT NULL) OR (approval_state <> 'Approved' AND approved_at_utc IS NULL AND approved_by_user_id IS NULL)");

                            t.HasCheckConstraint("ck_launch_targets_revision", "revision >= 1");
                        });
                });

            modelBuilder.Entity("JulOS.Infrastructure.Persistence.Core.NotificationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionLink")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("action_link");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DeduplicationKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("deduplication_key");

                    b.Property<DateTimeOffset?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at_utc");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("severity");

                    b.Property<string>("SourcePackageId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_package_id");

                    b.Property<string>("TitleKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title_key");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId", "DeduplicationKey")
                        .IsUnique()
                        .HasDatabaseName("ux_notifications_user_deduplication");

                    b.ToTable("notifications", "core");
                });

            modelBuilder.Entity("JulOS.Infrastructure.Persistence.Core.PackageInstallationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FaultCode")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("fault_code");

                    b.Property<string>("FaultDetail")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("fault_detail");

                    b.Property<DateTimeOffset?>("FaultedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("faulted_at_utc");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("package_id");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_package_installations");

                    b.ToTable("package_installations", "core", t =>
                        {
                            t.HasCheckConstraint("ck_package_installations_fault_metadata", "(state = 'Faulted' AND fault_code IS NOT NULL AND fault_detail IS NOT NULL AND faulted_at_utc IS NOT NULL) OR (state <> 'Faulted' AND fault_code IS NULL AND fault_detail IS NULL AND faulted_at_utc IS NULL)");

                            t.HasCheckConstraint("ck_package_installations_revision", "revision >= 1");
                        });
                });

            modelBuilder.Entity("JulOS.Infrastructure.Persistence.Core.PermissionAssignmentRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at_utc");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_user_id");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("permission");

                    b.Property<string>("ScopeId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("scope_id");

                    b.Property<string>("ScopeKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("scope_kind");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("subject_kind");

                    b.HasKey("Id")
                        .HasName("pk_permission_assignments");

                    b.HasIndex("SubjectKind", "SubjectId", "Permission", "ScopeKind", "ScopeId")
                        .IsUnique()
                        .HasDatabaseName("ux_permission_assignments_grant");

                    b.ToTable("permission_assignments", "core", t =>
                        {
                            t.HasCheckConstraint("ck_permission_assignments_scope", "(scope_kind = 'Global' AND scope_id IS NULL) OR (scope_kind <> 'Global' AND scope_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("JulOS.Infrastructure.Persistence.Core.ProblemRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcknowledgedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at_utc");

                    b.Property<Guid?>("AcknowledgedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("acknowledged_by_user_id");

                    b.Property<DateTimeOffset>("FirstDetectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_detected_at_utc");

                    b.Property<DateTimeOffset>("LastObservedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_observed_at_utc");

                    b.Property<int>("ObservationCount")
                        .HasColumnType("integer")
                        .HasColumnName("observation_count");

                    b.Property<string>("ProblemType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("problem_type");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("severity");

                    b.Property<string>("SourcePackageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_package_id");

                    b.Property<string>("StableResourceIdentity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("stable_resource_identity");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<string>("TitleKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title_key");

                    b.HasKey("Id")
                        .HasName("pk_problems");

                    b.HasIndex("SourcePackageId", "ProblemType", "StableResourceIdentity")
                        .IsUnique()
                        .HasDatabaseName("ux_problems_identity");

                    b.ToTable("problems", "core", t =>
                        {
                            t.HasCheckConstraint("ck_problems_observation_count", "observation_count >= 1");

                            t.HasCheckConstraint("ck_problems_revision", "revision >= 1");

                            t.HasCheckConstraint("ck_problems_state_timestamps", "(state = 'Active' AND acknowledged_at_utc IS NULL AND acknowledged_by_user_id IS NULL AND resolved_at_utc IS NULL) OR (state = 'Acknowledged' AND acknowledged_at_utc IS NOT NULL AND acknowledged_by_user_id IS NOT NULL AND resolved_at_utc IS NULL) OR (state = 'Resolved' AND resolved_at_utc IS NOT NULL) OR state = 'Suppressed'");
                        });
                });

            modelBuilder.Entity("JulOS.Infrastructure.Persistence.Core.SessionReferenceRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConnectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connected_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("failure_code");

                    b.Property<DateTimeOffset>("LastActivityAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at_utc");

                    b.Property<string>("LifecyclePolicy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("lifecycle_policy");

                    b.Property<string>("OwningPackageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("owning_package_id");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("SessionKind")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("session_kind");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("state");

                    b.Property<string>("TargetReference")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("target_reference");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_session_references");

                    b.ToTable("session_references", "core", t =>
                        {
                            t.HasCheckConstraint("ck_session_references_ended_at", "(state = 'Ended' AND ended_at_utc IS NOT NULL) OR (state <> 'Ended' AND ended_at_utc IS NULL)");

                            t.HasCheckConstraint("ck_session_references_expiry", "expires_at_utc IS NULL OR expires_at_utc > created_at_utc");

                            t.HasCheckConstraint("ck_session_references_revision", "revision >= 1");
                        });
                });

            modelBuilder.Entity("JulOS.Infrastructure.Persistence.Core.WidgetPlacementRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Column")
                        .HasColumnType("integer")
                        .HasColumnName("grid_column");

                    b.Property<Guid>("DesktopLayoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("desktop_layout_id");

                    b.Property<int>("HeightUnits")
                        .HasColumnType("integer")
                        .HasColumnName("height_units");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<int>("Row")
                        .HasColumnType("integer")
                        .HasColumnName("grid_row");

                    b.Property<string>("WidgetKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("widget_key");

                    b.Property<int>("WidthUnits")
                        .HasColumnType("integer")
                        .HasColumnName("width_units");

                    b.HasKey("Id")
                        .HasName("pk_widget_placements");

                    b.HasIndex("DesktopLayoutId");

                    b.ToTable("widget_placements", "core", t =>
                        {
                            t.HasCheckConstraint("ck_widget_placements_grid", "grid_column >= 0 AND grid_row >= 0 AND width_units > 0 AND height_units > 0 AND grid_column + width_units <= 64 AND grid_row + height_units <= 64");

                            t.HasCheckConstraint("ck_widget_placements_revision", "revision >= 1");
                        });
                });

            modelBuilder.Entity("JulOS.Infrastructure.Persistence.Core.AgentCapabilityRow", b =>
                {
                    b.HasOne("JulOS.Infrastructure.Persistence.Core.AgentRow", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_capabilities_agent");
                });

            modelBuilder.Entity("JulOS.Infrastructure.Persistence.Core.ApplicationViewportRow", b =>
                {
                    b.HasOne("JulOS.Infrastructure.Persistence.Core.ApplicationDefinitionRow", null)
                        .WithMany("SupportedViewports")
                        .HasForeignKey("ApplicationDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_viewports_application");
                });

            modelBuilder.Entity("JulOS.Infrastructure.Persistence.Core.DesktopWindowRow", b =>
                {
                    b.HasOne("JulOS.Infrastructure.Persistence.Core.ApplicationDefinitionRow", null)
                        .WithMany()
                        .HasForeignKey("ApplicationDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_desktop_windows_application");

                    b.HasOne("JulOS.Infrastructure.Persistence.Core.DesktopLayoutRow", null)
                        .WithMany("Windows")
                        .HasForeignKey("DesktopLayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_desktop_windows_layout");

                    b.HasOne("JulOS.Infrastructure.Persistence.Core.LaunchTargetRow", null)
                        .WithMany()
                        .HasForeignKey("LaunchTargetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_desktop_windows_launch_target");

                    b.HasOne("JulOS.Infrastructure.Persistence.Core.SessionReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("SessionReferenceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_desktop_windows_session");
                });

            modelBuilder.Entity("JulOS.Infrastructure.Persistence.Core.LaunchTargetRow", b =>
                {
                    b.HasOne("JulOS.Infrastructure.Persistence.Core.ApplicationDefinitionRow", null)
                        .WithMany()
                        .HasForeignKey("ApplicationDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_launch_targets_application");
                });

            modelBuilder.Entity("JulOS.Infrastructure.Persistence.Core.WidgetPlacementRow", b =>
                {
                    b.HasOne("JulOS.Infrastructure.Persistence.Core.DesktopLayoutRow", null)
                        .WithMany("Widgets")
                        .HasForeignKey("DesktopLayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_widget_placements_layout");
                });

            modelBuilder.Entity("JulOS.Infrastructure.Persistence.Core.ApplicationDefinitionRow", b =>
                {
                    b.Navigation("SupportedViewports");
                });

            modelBuilder.Entity("JulOS.Infrastructure.Persistence.Core.DesktopLayoutRow", b =>
                {
                    b.Navigation("Widgets");

                    b.Navigation("Windows");
                });
#pragma warning restore 612, 618
        }
    }
}
