export type SupportedLanguage = 'en' | 'de';

export const shellMessageKeys = [
  'about',
  'accessDenied',
  'agentStatus',
  'close',
  'commandPalette',
  'component',
  'desktop',
  'displayName',
  'launcher',
  'loading',
  'noApplicationsBody',
  'noApplicationsTitle',
  'notifications',
  'offline',
  'password',
  'passwordRequirements',
  'problems',
  'reference',
  'requestFailed',
  'serverUnavailable',
  'settings',
  'setupDescription',
  'setupInvalid',
  'setupRequired',
  'setupSubmit',
  'setupSubmitting',
  'setupTitle',
  'signedOut',
  'userName',
  'version',
] as const;

export type ShellMessageKey = (typeof shellMessageKeys)[number];

type ShellMessages = Readonly<Record<ShellMessageKey, string>>;

export const shellMessages: Readonly<Record<SupportedLanguage, ShellMessages>> = {
  en: {
    about: 'About JulOS',
    accessDenied: 'You do not have permission to view this information.',
    agentStatus: 'Agent status',
    close: 'Close',
    commandPalette: 'Search and commands',
    component: 'Component',
    desktop: 'Desktop',
    displayName: 'Display name',
    launcher: 'Open launcher',
    loading: 'Loading',
    noApplicationsBody: 'Open the launcher to start an installed application.',
    noApplicationsTitle: 'No applications are open',
    notifications: 'Notifications',
    offline: 'The JulOS server cannot be reached.',
    password: 'Password',
    passwordRequirements: 'At least 12 characters with uppercase, lowercase, number and symbol.',
    problems: 'Problems',
    reference: 'Reference',
    requestFailed: 'The request failed.',
    serverUnavailable: 'Server information unavailable',
    settings: 'Settings',
    setupDescription: 'Create the first administrator account for this JulOS installation.',
    setupInvalid: 'Check the entered values and try again.',
    setupRequired: 'Initial setup required',
    setupSubmit: 'Create administrator',
    setupSubmitting: 'Creating administrator…',
    setupTitle: 'Set up JulOS',
    signedOut: 'Sign in required',
    userName: 'Username',
    version: 'Version',
  },
  de: {
    about: 'Über JulOS',
    accessDenied: 'Du hast keine Berechtigung, diese Informationen anzuzeigen.',
    agentStatus: 'Agent-Status',
    close: 'Schließen',
    commandPalette: 'Suche und Befehle',
    component: 'Komponente',
    desktop: 'Desktop',
    displayName: 'Anzeigename',
    launcher: 'Launcher öffnen',
    loading: 'Wird geladen',
    noApplicationsBody: 'Öffne den Launcher, um eine installierte Anwendung zu starten.',
    noApplicationsTitle: 'Keine Anwendungen geöffnet',
    notifications: 'Benachrichtigungen',
    offline: 'Der JulOS-Server ist nicht erreichbar.',
    password: 'Passwort',
    passwordRequirements: 'Mindestens 12 Zeichen mit Großbuchstabe, Kleinbuchstabe, Zahl und Sonderzeichen.',
    problems: 'Probleme',
    reference: 'Referenz',
    requestFailed: 'Die Anfrage ist fehlgeschlagen.',
    serverUnavailable: 'Serverinformationen nicht verfügbar',
    settings: 'Einstellungen',
    setupDescription: 'Erstelle das erste Administratorkonto für diese JulOS-Installation.',
    setupInvalid: 'Prüfe die eingegebenen Werte und versuche es erneut.',
    setupRequired: 'Ersteinrichtung erforderlich',
    setupSubmit: 'Administrator erstellen',
    setupSubmitting: 'Administrator wird erstellt…',
    setupTitle: 'JulOS einrichten',
    signedOut: 'Anmeldung erforderlich',
    userName: 'Benutzername',
    version: 'Version',
  },
};

export function normalizeLanguage(value: string | null | undefined): SupportedLanguage {
  return value?.toLowerCase().startsWith('de') === true ? 'de' : 'en';
}

export function translate(language: SupportedLanguage, key: ShellMessageKey): string {
  return shellMessages[language][key];
}
