namespace JulOS.Domain.Primitives;

/// <summary>
/// Creates the stable identifiers of core entities.
/// </summary>
/// <remarks>
/// Identifiers are generated by Server, never by a client and never derived from an
/// external system, so they survive a container, virtual machine or route being
/// recreated. Generation is a port so tests produce deterministic identities.
/// </remarks>
public interface IIdentifierGenerator
{
    /// <summary>Returns a new identifier that has never been returned before.</summary>
    Guid Create();
}
